### ISSUE TITLE
Great theme! 👍🏼

### ISSUE THREAD

**Issue by flaviocopes** [ahmadawais/shades-of-purple-vscode#1]
I worked using this theme this afternoon, it's been a pleasure, I like the color theme 😀 

and I got used to the light ``` after a while it seemed natural 👍🏼

**Comment by ahmadawais** [comment]
I'm so happy to hear that @flaviocopes. Now long markdown files with code samples and other stencil punctuation won't feel that bad as it used to. 

I hope you will write a good 5-star review at [VSCode Marketplace](https://ahmda.ws/VSCSOP) as well.
