### ISSUE TITLE
Weird Vertical Bars showing up in integrated terminal !

### ISSUE THREAD

**Issue by itsmdsameerkhan** [ahmadawais/shades-of-purple-vscode#101]
This theme is one of my most favorite ♥ up to this date. However, I am facing a real issue here. The terminal shows a vertical bar that does not go away.

![image](https://user-images.githubusercontent.com/46621885/101653724-7ef94180-39f4-11eb-9a99-53ed3090a3dc.png)

Even after the screen has been cleared.

![image](https://user-images.githubusercontent.com/46621885/101653926-c253b000-39f4-11eb-85a7-1b2214578bf7.png)

Please have a fix 🤗! Else everything is awesome. 🍻

**Comment by ahmadawais** [comment]
I've no idea why that's happening — doesn't look like theme related. You should report it to the VSCode repo. And thanks for the kind words.
