### ISSUE TITLE
Open-vsx publishing?

### ISSUE THREAD

**Issue by bryphe** [ahmadawais/shades-of-purple-vscode#106]
Hi,

Thanks for your work on this awesome theme!

Would you be open to publishing this on the [open-vsx](https://open-vsx.org/) extension registry? This would make the theme available to VSCodium, GitPod, Onivim 2, and other editors that use the open registry.

There's some documentation here [https://github.com/eclipse/openvsx/wiki/Publishing-Extensions](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions) and in particular, once you have a token, there is a sample GitHub action to make it easy to publish: https://github.com/HaaLeo/publish-vscode-extension#readme

Would be great to see this extension there!

**Comment by ahmadawais** [comment]
Sure thing. I've asked to claim my namespace https://github.com/EclipseFdn/open-vsx.org/issues/442

**Comment by ahmadawais** [comment]
Done https://open-vsx.org/extension/ahmadawais/shades-of-purple

**Comment by bryphe** [comment]
Sweet, thanks @ahmadawais !
