### ISSUE TITLE
HTML Matching Tags Background Color

### ISSUE THREAD

**Issue by dwhenson** [ahmadawais/shades-of-purple-vscode#107]
Apologies if this is discussed elsewhere - I did a search but couldn't find anything. In my HTML it seems a default color is coming through when I have matching tags obscuring the lovelyness of SOP. Can you advise how to resolve this?

Screenshot attached.

Thanks for the top theme - I really love it. I also really loved your VS Code course thanks!!
<img width="1138" alt="Screenshot 2021-03-29 at 19 55 26" src="https://user-images.githubusercontent.com/50716370/112872398-02848e80-90c9-11eb-81e4-13d7fb7e6218.png">

**Comment by ahmadawais** [comment]
Hey @dwhenson thanks for the kind words. What default color are you talking about? Is it the highlighted div background color?

**Comment by ahmadawais** [comment]
Done in `v6.13` just released.

![image](https://user-images.githubusercontent.com/960133/114024193-31e78800-988d-11eb-8aae-5bd783830cc9.png)


Thank you! 🙌

**Comment by dwhenson** [comment]
Lovely thanks so much!!

**Comment by ahmadawais** [comment]
@dwhenson hope you can find some time to write a five star rating on https://ShadesOdPurple.pro/vscode and/or check out my courses at https://Awais.dev/courses

Thank you. 😊
