### ISSUE TITLE
Status bar text color is same as background color on debug mode

### ISSUE THREAD

**Issue by vhanla** [ahmadawais/shades-of-purple-vscode#11]
Status bar text color changes on entering to debug mode (F5), and it is impossible to see text there unless mouse cursor hovers, yet hovering shows a hard to read text color.
![image](https://user-images.githubusercontent.com/1015823/44468062-ff0ff900-a5e9-11e8-92b9-97dc3650a212.png)

OS: Windows 10

**Comment by ahmadawais** [comment]
@vhanla Oh boy, I didn't know if there was anything on debug screen. LOL. Fixing it now.

**Comment by ahmadawais** [comment]
Fixed in 🐛 Status Bar Debugging Foreground 26be3e0

**Comment by vhanla** [comment]
Thank you. However, if you notice using official themes (and many others), status bar background color changes from blue to orange on debug mode, it might not seem important, but it helps to know if we are still on debugging mode and if for some unknown reason debugger stopped, specially if we hide debugger sidebar or if it has been switched to file explorer sidebar for instance.

**Comment by ahmadawais** [comment]
@vhanla that's what I was thinking. I think it's worth taking another stab on this one. Can you open a new issue with this and I'll address that in the next release?
