### ISSUE TITLE
Add secondary button styles

### ISSUE THREAD

**Issue by miguelsolorio** [ahmadawais/shades-of-purple-vscode#110]
VS Code will start using the secondary button style in custom dialogs. These are visible on Windows and on the web (i.e. Codespaces). To see this:

1. [Install Insiders 1.56](https://builds.code.visualstudio.com/builds/insider)
2. Set `"window.dialogStyle": "custom",` in your user settings
3. Try to close an unsaved file that will prompt the dialog below

![image](https://user-images.githubusercontent.com/35271042/116309530-b7a87600-a75d-11eb-854a-ec4505fbdb76.png)

Since this is a newer color token, you'll need to add a few tokens:

- `button.secondaryBackground`
- `button.secondaryForeground`
- `button.secondaryHoverBackground`

**Comment by ahmadawais** [comment]
Oh, I didn't know this was available. Missed it. Recommend something and send in a PR.

**Comment by ahmadawais** [comment]
Thank you, I'm releasing a new version that fixes this and I'm excited. 

![CleanShot 2022-10-20 at 21 41 25](https://user-images.githubusercontent.com/960133/197113683-81e8bf7f-5ca8-4818-b4e3-eb897bfe3e8f.gif)
