### ISSUE TITLE
Remove blue box from "Highlight Matching Tag” extension.

### ISSUE THREAD

**Issue by M4H-i** [ahmadawais/shades-of-purple-vscode#112]
When I select a tag it highlights properly. but there appears a blue box around the tag I select. Which is very annoying.
How to solve this problem?
![Screenshot 2021-09-12 120242](https://user-images.githubusercontent.com/90303105/132977088-e7010fb7-7bc7-4907-806c-06191182258a.jpg)
.
.
![Screenshot 2021-09-12 120226](https://user-images.githubusercontent.com/90303105/132977092-dd15957f-ce26-4763-b218-02f37af77454.jpg)

**Comment by ahmadawais** [comment]
That doesn't look like my theme.

**Comment by ahmadawais** [comment]
And I believe you don't need that extension now that VS Code supports this natively. 

![image](https://user-images.githubusercontent.com/960133/197109446-a38f7b11-f25b-4156-9a2c-cc52bf34dab4.png)
