### ISSUE TITLE
Status bar on debug mode should show a distinct appearance

### ISSUE THREAD

**Issue by vhanla** [ahmadawais/shades-of-purple-vscode#12]
Many times, while we debug, the status bar color changes to a different color, preferably its background color is changed so it makes easier to notice whether debugging mode is running or not.

On some scenarios, we keep the debugger running while browsing (and even modifying live reload code, e.g. running a .Net Core web app). Sometimes, if we switch sidebar from debug view to file explorer, and debugger stops for unknown reasons (or interrupted manually), normally the status bar color would return to the initial (normal) color, so we would know that our work on the editor is not being debugged anymore.

While that scenario is expected, the current behavior of Shades Of Purple doesn't take that into consideration as most of the other themes do, and even sometimes we won't know if we have to stop the debugger since we might assume is not running, or the other way round. 

Considering `debug.toolBarLocation` is docked but not floating.

**Comment by ahmadawais** [comment]
Thanks for the suggestions. In v.2.8.0 I have added this new feature

![image](https://on.ahmda.ws/43979fb9f5e0/c)

👌 Status Bar Border + BG Colors df22f2b 
👌 Status Bar Highlight While Debugging b85e353
