### ISSUE TITLE
Nim Syntax highlight is not supported 

### ISSUE THREAD

**Issue by foxoman** [ahmadawais/shades-of-purple-vscode#133]
Am suing nim lang as my daily programming language.

But shades of purple is not supporting the language.

It is a compiled language with python like syntax.

* https://nim-lang.org/
* Example code used:

```
import murmurhash
import strutils

var mname: string = "nim"
let vversion: int = 1

# hashed password
func generateKey*(passphrase: string): string =
    let hashArray = MurmurHash3_x64_128(passphrase)
    return $hashArray[0] & $hashArray[1]
```

<img width="484" alt="image" src="https://user-images.githubusercontent.com/5356677/197226386-116c32b1-535d-4534-83c5-0dd557c1602e.png">

== This is how it looks like in Kimbi Dark+
<img width="382" alt="image" src="https://user-images.githubusercontent.com/5356677/197227252-8e961df8-3c56-4d46-a487-1ef0a6baa85d.png">

== This is how it looks like in the defualt VSCode DARK+ theme
<img width="396" alt="image" src="https://user-images.githubusercontent.com/5356677/197227596-34a709fc-f0b8-4a55-9ac1-6b56435329d9.png">

**Comment by ahmadawais** [comment]
Thanks. Do you have to install any extension to get the highlighting?

**Comment by ahmadawais** [comment]
I'm installing this lang pack as without it there is no native support? Tell me if this is the most used lang grammar?

https://marketplace.visualstudio.com/items?itemName=kosz78.nim

**Comment by ahmadawais** [comment]
Now I'm seeing the same syntax you shared above. 

<img width="585" alt="image" src="https://user-images.githubusercontent.com/960133/197243716-9ec13308-9c67-4dfb-b237-c780c933114d.png">


Working on adding support.

**Comment by foxoman** [comment]
Yes there is two ext. for nim support.

the recommended one is this which i use

https://marketplace.visualstudio.com/items?itemName=nimsaem.nimvscode

But both have same output.

**Comment by foxoman** [comment]
To have most of the syntax used I will recommend using this snippet from the offical nim website:

~~~
import std/strformat

type
  Person = object
    name: string
    age: Natural # Ensures the age is positive

let people = [
  Person(name: "John", age: 45),
  Person(name: "Kate", age: 30)
]

for person in people:
  # Type-safe string interpolation,
  # evaluated at compile time.
  echo(fmt"{person.name} is {person.age} years old")


# Thanks to Nim's 'iterator' and 'yield' constructs,
# iterators are as easy to write as ordinary
# functions. They are compiled to inline loops.
iterator oddNumbers[Idx, T](a: array[Idx, T]): T =
  for x in a:
    if x mod 2 == 1:
      yield x

for odd in oddNumbers([3, 6, 9, 12, 15, 18]):
  echo odd


# Use Nim's macro system to transform a dense
# data-centric description of x86 instructions
# into lookup tables that are used by
# assemblers and JITs.
import macros, strutils

macro toLookupTable(data: static[string]): untyped =
  result = newTree(nnkBracket)
  for w in data.split(';'):
    result.add newLit(w)

const
  data = "mov;btc;cli;xor"
  opcodes = toLookupTable(data)

for o in opcodes:
  echo o
~~~

Thank you very much for your kind support.

**Comment by ahmadawais** [comment]
Done! 
<img width="1217" alt="image" src="https://user-images.githubusercontent.com/960133/197247951-d0866ebf-97c8-47f3-ae22-cd7970e64fd5.png">


Nim support added to v7.1
https://marketplace.visualstudio.com/items?itemName=ahmadawais.shades-of-purple

> _P.S. You can always write a five-star review as sort of an appreciation for all the time I put into this theme — if interested click here to do that → [![Rating](https://img.shields.io/vscode-marketplace/r/ahmadawais.shades-of-purple.svg?label=Ratings&colorA=2D2A56&colorB=4D2AFF)](https://marketplace.visualstudio.com/items?itemName=ahmadawais.shades-of-purple#review-details)_

**Comment by foxoman** [comment]
Thank you very much :)
