### ISSUE TITLE
Super Dark's `textLink.foreground` color is hard to distinguish

### ISSUE THREAD

**Issue by zanedp** [ahmadawais/shades-of-purple-vscode#136]
The purple on the super dark purple is hard to read:
![image](https://user-images.githubusercontent.com/295055/205796443-937bfcdf-79c6-4ad9-8757-14d7121e0704.png)

A brighter color (like `#FAD000`) is easier to read:
![image](https://user-images.githubusercontent.com/295055/205797313-ef51b2f1-8d4d-48b7-bcb2-9d828bfc420b.png)

`textLink.activeForeground` should probably be adjusted as well, for when hovering over a link. (`#B362FF` is making me happy)

**Comment by jthk116** [comment]
Agreed. Love the super dark but that one detail is making it mostly unusable for me as it's being used often.

**Comment by zanedp** [comment]
Still a problem in v7.3.0:

![image](https://github.com/ahmadawais/shades-of-purple-vscode/assets/295055/3c8cca74-aa0e-46a4-ba67-acab116cb453)
