### ISSUE TITLE
Diff view looks weird

### ISSUE THREAD

**Issue by alankritjoshi** [ahmadawais/shades-of-purple-vscode#14]
Love your theme. Only gripe with it that I have is the diff view. It looks messed up with a green outline for each line, not sure if it is intended

<img width="1179" alt="screen shot 2018-09-10 at 2 20 41 pm" src="https://user-images.githubusercontent.com/13654555/45325069-c4242580-b504-11e8-8c42-c24c4e0a43c7.png">

**Comment by ahmadawais** [comment]
@alankritjoshi thanks for reaching out. It's very much intended. Outline is how you find out about changes in the same line. Give me a better example and I'll try my best to make 🦄 Shades of Purple better.

**Comment by alankritjoshi** [comment]
Oh cool, this seems to be something similar to one of the high contrast themes in Code. I was expecting a background highlight kind of thing because lines reduce visibility for me personally:

<img width="1145" alt="screen shot 2018-09-10 at 4 25 12 pm" src="https://user-images.githubusercontent.com/13654555/45329618-2c2f3780-b516-11e8-8ba3-e1faebc2c2e2.png">

I am rocking this theme regardless! Thanks for your contribution and for sharing on dev.to

**Comment by ahmadawais** [comment]
This is what it looks like without borders. That you can also do that by yourself by putting this in the settings.

```json
"workbench.colorCustomizations": {
		"diffEditor.insertedTextBorder": "#00FF000E",
		"diffEditor.removedTextBorder": "#FF000D1A",
	}
```

**WITHOUT**
![image](https://on.ahmda.ws/a4495c869394/c)

**WITH BORDERS**
![image](https://on.ahmda.ws/31fed87934dc/c)

I like it with borders, without borders it's too dull.

Peace! ✌️

**Comment by ansemjo** [comment]
I :heart_eyes: this theme! However, this is the one thing that kinda looks weird to me.

I agree that without the borders it looks dull. On the other hand the sheer number of borders when you have many changed lines in one block looks messy, too. If there was a way to collapse intersecting borders so they do not appear bolder than the rest, that would help a lot, I believe.

Toning the borders down a bit and instead brightening the background, the override that I am currently using:
```json
{
  ...
  "workbench.colorCustomizations": {
        "[Shades of Purple]": {
            "diffEditor.insertedTextBorder": "#0f04",
            "diffEditor.insertedTextBackground": "#0f02",
            "diffEditor.removedTextBorder": "#f004",
            "diffEditor.removedTextBackground": "#f002"
        }
    }
}
```
