### ISSUE TITLE
Fix file comparison interface display

### ISSUE THREAD

**Issue by jt3k** [ahmadawais/shades-of-purple-vscode#140]
could you remove the banding in the comparison interface?
Now it looks trashy and in the way.
I checked other vscode themes and almost everywhere I see this interface without green lines.

<img width="555" alt="image" src="https://github.com/ahmadawais/shades-of-purple-vscode/assets/1261240/2f1c5a6d-7ded-4f35-b2ff-b0ad83c97003">

**Comment by jt3k** [comment]
@ahmadawais BUMP UP!

**Comment by ahmadawais** [comment]
What do you mean? Diff is supposed to be like that. Help me understand the part you want improved?

My guess is removing border but keeping green/red without strong border lines?

Can you share and pin point more with what you want? Happy to fix.

**Comment by ahmadawais** [comment]
I'm trying to understand what y'all need. Right now I personally use semantic diff. 

BEFORE with VSCode Diff
<img width="631" alt="image" src="https://github.com/ahmadawais/shades-of-purple-vscode/assets/960133/3cf922b3-5d2a-4b15-9343-1a5795f1b4b3">

AFTER with SemanticDiff
<img width="643" alt="image" src="https://github.com/ahmadawais/shades-of-purple-vscode/assets/960133/6eeb496f-7569-4cc1-b978-7b9206dd64c7">

This is how you use it. And Shades of Purple works great in that mode. I'm gonna make the other one support similar colors based on y'all's feedback.

![screenshot-2024-02-27-at-02 58 54PM](https://github.com/ahmadawais/shades-of-purple-vscode/assets/960133/ffd3432e-c437-4cf5-bad1-7e0569e21a65)

**Comment by gangov** [comment]
hey @ahmadawais the 2nd screenshot with SemanticDiff looks nicer

**Comment by ahmadawais** [comment]
@gangov You can use that in VSCode already :)

**Comment by gangov** [comment]
@ahmadawais when I'm using the default Visual Studio Code theme the git difference are shown without any borders on top of the green/red background. However using this theme I get the borders. Am I using some defaults, if so, how can I get rid of those borders as shown in your 1st screenshot?

**Comment by ahmadawais** [comment]
Fixed!!

🚀  Published ahmadawais.shades-of-purple v7.3.0
 INFO  Extension URL (might take a few minutes): https://marketplace.visualstudio.com/items?itemName=ahmadawais.shades-of-purple
 INFO  Hub URL: https://marketplace.visualstudio.com/manage/publishers/ahmadawais/extensions/shades-of-purple/hub
 DONE  Published ahmadawais.shades-of-purple v7.3.0.
