### ISSUE TITLE
Invalid Hex Color Code

### ISSUE THREAD

**Issue by ghost** [ahmadawais/shades-of-purple-vscode#143]
The hex color code written on `importCost.largePackageColor` for import cost extension is invalid.

```
// SOP's Import Cost Extension Settings.
"importCost.largePackageColor": "#EC3A37F5",
...
```

It is found in `README.md` under section **Best Custom Settings**.

**Comment by ahmadawais** [comment]
Please send a PR.

**Comment by ahmadawais** [comment]
Just checked, it's not invalid, it's translucent and modern with light color. Should work fine.
