### ISSUE TITLE
Package.json script section color not visible 

### ISSUE THREAD

**Issue by rashnk** [ahmadawais/shades-of-purple-vscode#145]
**Theme:** 
Shades of purple(super dark)

**Issue:**
The text is not visible on hover popup/tooltip on package.json scripts section

**Reproduce:**
hover on package.json scripts item,  dev, the popup with text **Run Script | Debug script**
```
"scripts": {
    "dev": "vite",
    "dev-host": "vite --host",
    "build": "vue-tsc --noEmit && vite build",
    "preview": "vite preview",
    "lint": "eslint . --fix --ignore-path .gitignore"
  },
```

**Demo**
https://github.com/ahmadawais/shades-of-purple-vscode/assets/12730428/381997ab-75c8-4ca0-9bbf-8f989294497d

**Comment by ahmadawais** [comment]
True that, wanna send in a PR?

**Comment by rashnk** [comment]
don't know what to change

**Comment by black-black-cat** [comment]
What I'm experiencing is that it defaults to yellow here and light purple on hover👇
![屏幕截图 2024-03-29 095917](https://github.com/ahmadawais/shades-of-purple-vscode/assets/15521864/c0db59f6-a106-4ebf-8182-82087b53716e)

**Comment by ahmadawais** [comment]
Yep fixed now.
