### ISSUE TITLE
Active sidebar button is not highlighted

### ISSUE THREAD

**Issue by Yanpas** [ahmadawais/shades-of-purple-vscode#17]
Here every button is solid white, it's not obvious which is selected. Is it by design?
![image](https://user-images.githubusercontent.com/7345761/45546637-8be35680-b826-11e8-8542-a734de33dc18.png)

**Comment by ahmadawais** [comment]
@Yanpas that is a bug. Do you have any idea what property it is? I am searching on my end.

**Comment by Yanpas** [comment]
I see two options:
* white and grey
* yellow and white
* purple and white

I think the first one is better since it is less distractive and yellow is already used for badges. The grey hue should be purple a bit.

By the way, what do you think about yellow status bar? I like preinstalled vscode themes for their blue/purple/orange status bar, it makes theme less boring.

**Comment by ahmadawais** [comment]
I was not asking for that, I was looking for a way to configure that. There's no way for me to do that now. Since I cannot target the active and inactive foreground colors in the activity bar. 

My research led me to https://github.com/Microsoft/vscode/pull/58517 which means this is a feature we'll have in the next release. It was merged yesterday.

After that I'll play around with a shade of purple (inactive) and white (active) for the activity bar. 

Peace! ✌️

**Comment by ahmadawais** [comment]
>By the way, what do you think about yellow status bar? I like preinstalled vscode themes for their blue/purple/orange status bar, it makes theme less boring.

When you are in the debug mode your status bar should turn yellow in 🦄 Shades of Purple. Take a look → https://vscode.pro/tip/17

If you want to change that, use a workbench setting to further customize it the way you want :)

**Comment by ahmadawais** [comment]
This was fixed in the latest version. 

![image](https://on.ahmda.ws/737984/c)

**Comment by Yanpas** [comment]
Great, thanks!

**Comment by ahmadawais** [comment]
This feature came out in the latest release and I had it fixed in a couple of hours. It feels great to be focused on one of my open source projects like this. 

@Yanpas 

> _P.S. You can always write a five-star review as sort of an appreciation for all the time I put into this theme — if interested click here to do that → [![Rating](https://img.shields.io/vscode-marketplace/r/ahmadawais.shades-of-purple.svg?label=Ratings&colorA=2D2A56&colorB=4D2AFF)](https://marketplace.visualstudio.com/items?itemName=ahmadawais.shades-of-purple#review-details)_

**Comment by Yanpas** [comment]
Done 🤝

**Comment by ahmadawais** [comment]
Thanks a million 👌

>
