### ISSUE TITLE
👌 Matching styles for the “Highlight Matching Tag” extension?

### ISSUE THREAD

**Issue by ahmadawais** [ahmadawais/shades-of-purple-vscode#20]
### Question

Do you have a matching style for using the “Highlight Matching Tag” extension?

### Answer: `YES`

1. Install [Highlight Matching Tag](https://marketplace.visualstudio.com/items?itemName=vincaslt.highlight-matching-tag) extension.
2. Add the following settings to your `settings.json` file

``json
"highlight-matching-tag.style": {
    "backgroundColor": "rgba(165, 153, 233, 0.3)"
},
"highlight-matching-tag.leftStyle": {
    "borderWidth": "0"
},
"highlight-matching-tag.rightStyle": {
    "borderWidth": "0"
},
```

Peace! ✌️

**Comment by kaosmos** [comment]
as of [Highlight Matching Tag](https://marketplace.visualstudio.com/items?itemName=vincaslt.highlight-matching-tag) v 0.8+ the styling options are changed.This is the new equivalent code:

````
"highlight-matching-tag.styles": {
    "opening": {
      "full": {
        "custom": {
          "backgroundColor": "rgba(165, 153, 233, 0.3)"
        }
      },
      "left": {
        "custom": {
          "borderWidth": "0"
        }
      },
      "right": {
        "custom": {
          "borderWidth": "0"
        }
      }
    }
  }`

**Comment by ahmadawais** [comment]
@kaosmos you are right. I have updated the comment above. These styles were automagically migrated on update.

**Comment by ahmadawais** [comment]
### Before v0.9.1

```json
// SOP's highlight matching tag setting.
"highlight-matching-tag.styles": {
		"opening": {
			"full": {
				"custom": {
					"backgroundColor": "rgba(165, 153, 233, 0.1)"
				}
			},
			"left": {
				"custom": {
					"borderWidth": "0"
				}
			},
			"right": {
				"custom": {
					"borderWidth": "0"
				}
			}
		}
	},

```

### After v0.9.1

```json
// SOP's highlight matching tag setting.
"highlight-matching-tag.styles": {
    "opening": {
        "full": {
            "highlight": "rgba(165, 153, 233, 0.3)"
        }
    }
},
```
