### ISSUE TITLE
Improve hover color on sub menus

### ISSUE THREAD

**Issue by webribs** [ahmadawais/shades-of-purple-vscode#21]
Whenever I hover on any menu / sub menu it should show dark color of purple. 

currently same color is also applied on hover.

**Comment by ahmadawais** [comment]
Kindly post a screenshot!

**Comment by webribs** [comment]
In my workspace it good 
![vscode](https://user-images.githubusercontent.com/10451770/47636413-061f2e80-db7a-11e8-90f5-22798a9f1d89.png)


Check the menu background color on hover:
![vscode1](https://user-images.githubusercontent.com/10451770/47636415-061f2e80-db7a-11e8-880c-3d3506c5da0c.png)

**Comment by ahmadawais** [comment]
This should be fixed in the [latest release v3.17.0](https://github.com/ahmadawais/shades-of-purple-vscode/blob/master/CHANGELOG.md#release-3170) — update your theme and let me know if it's not (since I don't use Windows and my menu is OS based).

Peace! ✌️
