### ISSUE TITLE
Font letter spacing issue

### ISSUE THREAD

**Issue by bpkennedy** [ahmadawais/shades-of-purple-vscode#22]
Hi, love the theme!

I have noticed that double 'f' followed by an 'i' produces this weird font letter spacing issue.  I'm not sure if this is related to choices you made in your theme or choices I made in my settings.  :) . Does this happen for you, as well?

<img width="345" alt="screen shot 2018-11-20 at 9 17 55 am" src="https://user-images.githubusercontent.com/5321664/48783212-7286dc80-eca5-11e8-816c-bad0f26cee24.png">

**Comment by ahmadawais** [comment]
@bpkennedy thanks a lot for liking this theme. Built it to make things consistent and throughout, all of my course is based on it, [the VSCode Power User → ](https://VSCode.pro/)

About the issue, you're talking about. This is definitely a font issue. May I suggest [IBM Plex Mono](https://github.com/IBM/plex/tree/master/IBM-Plex-Mono)? I know this, coz there are no settings in the theme that can make a font go like this.

My course is on [40% off as a launch price](https://VSCode.pro/), I share my entire setup in there if you're interested.

Peace! ✌️

**Comment by bpkennedy** [comment]
Thanks, that did the trick!

**Comment by ahmadawais** [comment]
Yay!!! 🙌
