### ISSUE TITLE
editor.findMatchBackground default color problem

### ISSUE THREAD

**Issue by kaosmos** [ahmadawais/shades-of-purple-vscode#24]
Hello there,
I'm having a lot of readability problems with the default highlight color for search results.
It is a fully saturated orange (i.e. #FF7200) and, especially with some code highlights, the search result is very hard to read.

I attach a screenshot to show my point:

![color_highlight_difficulties](https://user-images.githubusercontent.com/138006/49594563-69209400-f976-11e8-88e9-4c6351fe7bbc.png)

I'm currently overriding this in my settings.json but I'd prefer a more readable color in the theme.

**Comment by ahmadawais** [comment]
@kaosmos what color would you suggest? I have seen that with syntax highlighting this orange colors works the best. It's the same that Google Search & Chrome use.

**Comment by kaosmos** [comment]
@ahmadawais yes I noticed it :) but Google Search and Chrome usually highlights a black text and this color works but in your boldly (and very pleasing I have to say) mixed palette there are too many colors to cope with.
Right now I'm using #DAD5F6, it is a very very light version of your chosen foreground color, not completely satisfied but it works better for me.

**Comment by ahmadawais** [comment]
@kaosmos yes, that `#DAD5F6` works too. I seriously threw many shades of purple on the search highlight but nothing worked as good with all the different colors. 

I am going to keep this issue open in hope that someone will make a better suggestion than what we have right now. I don't like it either — but with most colors, it does the highlighting. 

Also, glad to see you like the theme. Can I ask for a 🌟 [five-star rating](https://marketplace.visualstudio.com/items?itemName=ahmadawais.shades-of-purple#review-details) this helps me with the theme discovery for so many devs out there? 

Also, not sure if you've got a chance to check out the course I just released, easily my best work, it's called [VSCode.pro](https://VSCode.pro) — worked quite hard on this course and if you ever think of supporting my work — buying this course would be the right way to do it. 

Peace! ✌️

**Comment by kaosmos** [comment]
> Also, glad to see you like the theme. Can I ask for a 🌟 [five-star rating](https://marketplace.visualstudio.com/items?itemName=ahmadawais.shades-of-purple#review-details) this helps me with the theme discovery for so many devs out there?

Absolutely, I just did it, and thank you for making this theme available to the rest of us

**Comment by ahmadawais** [comment]
@kaosmos Thank you, for sharing the feedback and this review! 😇

**Comment by kaosmos** [comment]
@ahmadawais, a quick heads up on this: now VS Code support opacity for background colors, now my chosen color for the find match highlight is:
`"editor.findMatchHighlightBackground": "#FF7200A0"`

**Comment by ahmadawais** [comment]
Thanks for letting me know. I just pushed an update 👍

**Comment by kaosmos** [comment]
❤️ lovely, also I like the slightly different color you chose. thank you

**Comment by ahmadawais** [comment]
Yeah, I wanted the color to pop a little. Peace! ✌️
