### ISSUE TITLE
I would like to distinguish variable assignments (var/let/const/etc...) from statements (for/while/break/class/etc..)

### ISSUE THREAD

**Issue by d0ppler1977** [ahmadawais/shades-of-purple-vscode#26]
Is it possible to get a different color for the variable assignments?
![shades_of_purple_issue](https://user-images.githubusercontent.com/34218496/50149883-aa8d3980-02bc-11e9-8e21-0d4d30205d85.JPG)

The standard theme (Dark +) does this:
![shades_of_purple_issue_explaining](https://user-images.githubusercontent.com/34218496/50149889-ae20c080-02bc-11e9-9c0b-d306a798459c.JPG)

**Comment by ahmadawais** [comment]
@d0ppler1977 can you send me the code you have there? Also point out the keywords you want with different colors. I will look over to what can be done. 👍

**Comment by d0ppler1977** [comment]
I cannot post js-files, but here's an example:
```
var a_var_variable = "foo";
let a_let_variable = "bar";
const a_constant = "Shades of Purple is awesome";
for (let i = 0; i < a_constant.length; i++) {
    console.log(a_constant);
    if (i > 10) break;
}
return 0;
```


just paste this into a file with .js extension.

Basically, I only want these three keywords i different colors:

- let
- var
- const

**Comment by ahmadawais** [comment]
@d0ppler1977 I do understand what you mean. I am on vacations. I have every intention of fixing this and making 🦄 Shades of Purple better. Just bear with me a little.

**Comment by ahmadawais** [comment]
@d0ppler1977 I can confirm that the default theme has the same colors as well. 

![image](https://user-images.githubusercontent.com/960133/50321817-7dc36700-04f4-11e9-84bb-a14dd97d6ecb.png)

**Comment by ahmadawais** [comment]
So, I tested about 10 themes and almost every other theme has the keywords and storage types with same colors. I tried different theme colors and it didn't look good. So, I am not going to change any of the colors for storage types.

But, I can offer you a solution that you can use to set whatever color you like. 

In your settings.json file set this:

```json
"editor.tokenColorCustomizations": {
		"[Shades of Purple]": {
			"textMateRules": [
				{
					"name": "[JAVASCRIPT] — Storage types",
					"scope": [
						"storage.type.js",
					],
					"settings": {
						"foreground": "#FAD000"
					}
				},
			]
		}
	}
```

Change the foreground color to whatever fits the bill for you. 

Here's a demo:

![image](https://on.ahmda.ws/2de537/c)

---

🦄 **Shades of Purple** theme is free and open source. I provide support on my personal time. You can support my work by purchasing my [VSCode.pro](https://VSCode.pro) course _Easily my best work_.


> _P.S. You can always write a five-star review as sort of an appreciation for all the time I put into this theme — if interested click here to do that → [![Rating](https://img.shields.io/vscode-marketplace/r/ahmadawais.shades-of-purple.svg?label=Ratings&colorA=2D2A56&colorB=4D2AFF)](https://marketplace.visualstudio.com/items?itemName=ahmadawais.shades-of-purple#review-details)_
