### ISSUE TITLE
Shades of Purple Not Working

### ISSUE THREAD

**Issue by nxm67420** [ahmadawais/shades-of-purple-vscode#27]
Hello, I am trying to obtain the shades of purple theme which will not work for my device. All other themes I download work perfectly fine except for this one which will not show anything. I am currently using 2017 MacBook Pro running macOS Majave 10.14.2./ Visual Studio Code is up to date as well.
I've tried all current methods of installing even changing the default theme manually, but still nothing.
*List of current extensions installed
-C/C++
-Code Runner
-Debugger for Java
-Java Debug
-Java Extension Pack
-Java Test Runner
-Language Support for Java(TM) by Red Hat
-Maven for Java 
-Python 
-Winter is Coming Theme
Thank You!!

**Comment by ahmadawais** [comment]
That is extremely strange. Can you use CloudApp to make a GIF/Video and send here so I could see what happens? Since I am not able to reproduce the issue.

**Comment by nxm67420** [comment]
Sure.. https://cl.ly/a56113e2b6bc <https://cl.ly/a56113e2b6bc>

**Comment by OthmanAmoudi** [comment]
i was exactly going through this issue ! all other installed themes can be applied but not 'Shades of Purple' !! after going all tests, test #3 worked for me ! thanks

**Comment by ahmadawais** [comment]
@OthmanAmoudi so it works for you in the Insiders version and not in the regular one? What OS are you on?

**Comment by OthmanAmoudi** [comment]
i'm using macOS Mojave 😄

**Comment by ahmadawais** [comment]
I hope it's all well now.
