### ISSUE TITLE
Docker syntax highlighting

### ISSUE THREAD

**Issue by mpfeil** [ahmadawais/shades-of-purple-vscode#28]
Hi @ahmadawais,

first off thank you for this great theme (loving it) and your perfect vscode pro course.
I have installed VSCode (`1.30.2`) with the official Docker extension (version `0.5.0`) and SOP theme (`4.4.0`).

With SOP theme turned on there is no docker syntax highlighting.
![vscode_sop_docker](https://user-images.githubusercontent.com/2471172/50885970-76a2c100-13ef-11e9-8782-e06f21e05816.PNG)

Changing the theme back to e.g. `Dark (Visual Studio)` highlighting is working:
![vscode_dark_docker](https://user-images.githubusercontent.com/2471172/50886049-bb2e5c80-13ef-11e9-905b-dd6188414938.PNG)

I´ve tried to find the right place to adjust the highlighting but I have no clou where to start. Maybe you can give me a hint where to start and I can contribute.

**Comment by ahmadawais** [comment]
@mpfeil thanks for the kind words. Glad to see you are enjoying the course and my theme. 

Can you send me the links to docker extension and the code with file type so I can improve the theme with that syntax colors. 👍

**Comment by mpfeil** [comment]
This is the link to the [extensions](https://marketplace.visualstudio.com/items?itemName=PeterJausovec.vscode-docker)

And you can use the example `Generating Docker Files` from the extension page. So the file is just called `Dockerfile`

**Comment by ahmadawais** [comment]
We just got new syntax here :)

![docker](http://on.ahmda.ws/9b7205)

Update to 4.16.0
