### ISSUE TITLE
Issue with terminal errors

### ISSUE THREAD

**Issue by HasnainAshfaq** [ahmadawais/shades-of-purple-vscode#3]
Ahmad, first of all great theme! Its not an issue it is a suggestion.

On Retina display the errors on terminal look fine. But on non-retina displays they look bloody red. Maybe making them a bit bright would do a great job. 

Again, its a wonderful theme, thanks!

![screen shot 2018-04-10 at 5 50 11 pm](https://user-images.githubusercontent.com/11078828/38557884-e7e1cf8a-3ce7-11e8-8f7e-5d846ab7b6de.png)

**Comment by ahmadawais** [comment]
@HasnainAshfaq I think the that looks fine. There doesn't seem to be a way to target windows differently. What's causing this issue is that you are using a bold font on your terminal. Replace it with a medium bold or thin font and report back?

**Comment by ahmadawais** [comment]
@r00t8 Can you try Shades of Purple with iTerm2 → https://github.com/ahmadawais/shades-of-purple-iterm2

Also make sure you set both fonts. A powerline font is missing in your settings. 

Also, for SOP-VSCode keep these settings → https://ahmda.ws/2ILQoE1

**Comment by ahmadawais** [comment]
Glad to know that. Closing this one.
