### ISSUE TITLE
Javascript Object keys are trated as strings 

### ISSUE THREAD

**Issue by enderakpil** [ahmadawais/shades-of-purple-vscode#31]
Java Script Object Keys and values get some highlighting rules.

![shadeofpurple](https://user-images.githubusercontent.com/1410252/53442613-c169ae00-3a1a-11e9-9ccb-7a172ddde991.jpg)

Maybe below syntax can help to solve problem.

{
            "name": "[JAVASCRIPT] - Color for OBJECT KEY",
            "scope": "string.unquoted.js,constant.other.object.key.js",
            "settings": {
                "foreground": "#f36608"
            }
        },

**Comment by ahmadawais** [comment]
For this code.

```js

const removeExpense = ({id} = {}) => ({
  type: "REMOVE EXPENSE",
  expense: {
    id: id
  }
})

```

I get this highlighting:

![](https://on.ahmda.ws/472d93)

Not sure why it's the same on your end. Since it's solved, I'll close the issue for now. Feel free to repoen or discuss further.

**Comment by enderakpil** [comment]
Could you tell me the token name and which grammar do you use?

**Comment by ahmadawais** [comment]
I am using the default theme 🦄 Shades of Purple without any changes and `JavaScript` is selected as the languge.
