### ISSUE TITLE
color not change when Commented-Out Code

### ISSUE THREAD

**Issue by oceanlvr** [ahmadawais/shades-of-purple-vscode#32]
sorry to disturb. when I Commented-Out Code. comment color doesn't change.

![image](https://user-images.githubusercontent.com/36698124/54665867-36646b00-4b23-11e9-8efa-b847b7539547.png)

**Comment by ahmadawais** [comment]
I need more info. Paste all code. File name. Extension. Could be another extension have you tried disabling all extensions from command palette and just enabling the theme and then one by one enabling extensions to find out when it goes wrong.

Version of your VSCode.
