### ISSUE TITLE
Syntax highlighting for SQL strings

### ISSUE THREAD

**Issue by sfrench87** [ahmadawais/shades-of-purple-vscode#33]
It would be great to get SQL strings fully supported, with highlighting of functions/keywords etc.

**Comment by ahmadawais** [comment]
Give me code examples with code so I can test and make it better. Both pics and code.

**Comment by sfrench87** [comment]
Hi, i've attached screenshots of sop and monokai pro, to show the difference.

And here's some PHP
```
$test = "SELECT req_id, cCode, inst, course_isn-10000 AS course_isn, venue, areaName, courseTitle, DATE_FORMAT(startDate, '%D %b %Y')
  AS startDate, endDate, dow, startTime, endTime, noWeeks, tutor, fee, concessions, courseArea, publicSite, whoFor, whatLearn, content, equipment, workOutside, assessment, whatNext, otherCosts, brochureText, teachMethod, webEnrol
  FROM SETUPConfirmedWeb W
  INNER JOIN SETUPCourseArea A ON W.courseArea = A.area_id
  WHERE courseTitle = (SELECT courseTitle FROM SETUPConfirmedWeb WHERE req_id = $IDS) AND venue = (SELECT venue FROM SETUPConfirmedWeb WHERE req_id = $IDS)
    AND TIMESTAMPDIFF(DAY, NOW(), startDate) >= -60 AND publicSite = 1"
```

![Capture](https://user-images.githubusercontent.com/48254143/54928928-a3557780-4f0c-11e9-8f0a-519318f6b556.JPG)
![Capture2](https://user-images.githubusercontent.com/48254143/54928933-a5b7d180-4f0c-11e9-8255-e4e0e7a2c580.JPG)

**Comment by sfrench87** [comment]
Hi i've come up with a few changes that work for me, if it helps at all plus a small regex string fix

`{
          "scope": ["source.sql"],
          "settings": {
            "foreground": "#ffffffff"
          }
        },
        {
          "scope": ["source.sql keyword.other"],
          "settings": {
            "foreground": "#ff9d00ff"
          }
        },
        {
          "scope": ["source.sql support.function"],
          "settings": {
            "foreground": "#FAD000"
          }
        },
        {
          "name": "RegExp String",
          "scope": ["string.regexp", "string.regexp keyword.other"],
          "settings": {
            "foreground": "#ffffffff"
          }
        }`
![Capture2](https://user-images.githubusercontent.com/48254143/54991213-5b8a2b00-4fb4-11e9-9d9e-2c465749d12a.JPG)
![Capture](https://user-images.githubusercontent.com/48254143/54991215-5b8a2b00-4fb4-11e9-8730-b09f5c6e610e.JPG)

**Comment by ahmadawais** [comment]
DONE  Published ahmadawais.shades-of-purple@4.13.0

You should see the changes in the latest version. Thanks for the help. 



> _P.S. You can always write a five-star review as sort of an appreciation for all the time I put into this theme — if interested click here to do that → [![Rating](https://img.shields.io/vscode-marketplace/r/ahmadawais.shades-of-purple.svg?label=Ratings&colorA=2D2A56&colorB=4D2AFF)](https://marketplace.visualstudio.com/items?itemName=ahmadawais.shades-of-purple#review-details)_
