### ISSUE TITLE
More Robust Rust Language Support?

### ISSUE THREAD

**Issue by macintacos** [ahmadawais/shades-of-purple-vscode#35]
It doesn't appear that this theme handles Rust very well, at least with keywords in comparison to other languages. Example:

![](https://cl.ly/41d8a14387d6/Image%202019-04-13%20at%2011.19.53%20PM.png)

Specifically, the `use` statements (including the `std`/`io`/`rand`/`Rng`/etc.), `let`, and `fn` could use some color, as well as (potentially?) the variables. I'm actually just learning Rust now, so I'm not exactly sure about all of the reserved words in the language, but those are a few that stick out to me right now from this small code example.

[Here's documentation for the list of Rust keywords](https://doc.rust-lang.org/book/appendix-01-keywords.html) (not sure if that helps!)

**Comment by ahmadawais** [comment]
Update coming soon!

**Comment by ahmadawais** [comment]
@macintacos Can you send me this code sample here?

**Comment by macintacos** [comment]
@ahmadawais sure, it’s actually from the Rust Lang book available online here: https://doc.rust-lang.org/book/ch02-00-guessing-game-tutorial.html#generating-a-random-number

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ahmadawais** [comment]
Updated in v5.0 🎉

![rust](https://on.ahmda.ws/9cfa47/c)

**Comment by ahmadawais** [comment]
std/io/rand/Rng etc don't have any syntax definitions in this extension https://marketplace.visualstudio.com/items?itemName=rust-lang.rust

Peace! ✌️
