### ISSUE TITLE
[Feature Request] Matching styles for the “Indent-Rainbow” extension?

### ISSUE THREAD

**Issue by demartini** [ahmadawais/shades-of-purple-vscode#36]
Hi,

First of all, thanks for this amazing theme, I was using Dracula Theme, but when I met Purple I fell in love. 🦄 

I'm crazy about code indentation, and to help me in this task I use the [Indent-Rainbow ](https://marketplace.visualstudio.com/items?itemName=oderwat.indent-rainbow) extension, I'd like to know if it would be possible for you to provide the matching styles as you did for the [Highlight Matching Tag](https://github.com/ahmadawais/shades-of-purple-vscode/issues/20) extension?

Thank you in advance for your attention.

**Comment by ahmadawais** [comment]
Glad to know that you like the theme. 

Check the FAQs https://github.com/ahmadawais/shades-of-purple-vscode#frequently-asked-questions

-  Highlight Matching Tag styles for SOP: https://github.com/ahmadawais/shades-of-purple-vscode/issues/20

I don't like and use Indent-Rainbow, but I can create helpful styles for it. Give me some time.

> _P.S. You can always write a five-star review as sort of an appreciation for all the time I put into this theme — if interested click here to do that → [![Rating](https://img.shields.io/vscode-marketplace/r/ahmadawais.shades-of-purple.svg?label=Ratings&colorA=2D2A56&colorB=4D2AFF)](https://marketplace.visualstudio.com/items?itemName=ahmadawais.shades-of-purple#review-details)_

>> You can also purchase [VSCode Power User Course](https://VSCode.pro) to support my work and become a [VSCode.pro →](https://VSCode.pro)

**Comment by ahmadawais** [comment]
Here you go for Indent-rainbow → https://github.com/ahmadawais/shades-of-purple-vscode/issues/37

**Comment by demartini** [comment]
Many thanks for the support, I've already written a review in the market.

**Comment by ahmadawais** [comment]
Thank you! 👌
