### ISSUE TITLE
👌 Matching styles for the “Indent-Rainbow” extension?

### ISSUE THREAD

**Issue by ahmadawais** [ahmadawais/shades-of-purple-vscode#37]
### Question

Do you have a matching style for using the “Indent-Rainbow” extension?

### Answer: `YES`

1. Install [Indent-Rainbow](https://marketplace.visualstudio.com/items?itemName=oderwat.indent-rainbow) extension.
2. Add the following settings to your `settings.json` file

```json
"indentRainbow.colors": [
    "rgba(165, 153, 233,0.5)",
    "rgba(165, 153, 233,0.4)",
    "rgba(165, 153, 233,0.3)",
    "rgba(165, 153, 233,0.2)",
    "rgba(165, 153, 233,0.1)"
],
```

Peace! ✌️

**Comment by barsikus007** [comment]
for Shades of Purple (Super Dark) theme
(I divided rgb values of `editor.background` from original theme by super dark ones, and then multiplied on `indentRainbow.colors` values)

```json
"indentRainbow.colors": [
    "rgba(92, 85, 132 ,0.5)",
    "rgba(92, 85, 132 ,0.4)",
    "rgba(92, 85, 132 ,0.3)",
    "rgba(92, 85, 132 ,0.2)",
    "rgba(92, 85, 132 ,0.1)"
],
```
