### ISSUE TITLE
Alfred theme

### ISSUE THREAD

**Issue by 0x77dev** [ahmadawais/shades-of-purple-vscode#38]
[Shades of Purple Theme for Alfred](https://github.com/ahmadawais/shades-of-purple-vscode/files/3125437/Shades.of.Purple.zip)

> Uploaded in zip because Github doesn't allow to upload Alfred theme file type

![Theme Preview](https://user-images.githubusercontent.com/46429701/56869308-bf66a000-6a07-11e9-9ad9-2d80c42a3258.png)

**Comment by ahmadawais** [comment]
There's already an Alfred theme 

https://github.com/ahmadawais/shades-of-purple-vscode#put-shades-of-purple-in-other-places

→ DIRECT LINK: https://github.com/ahmadawais/shades-of-purple-alfred
