### ISSUE TITLE
Better distinguish tooltips

### ISSUE THREAD

**Issue by rdhar** [ahmadawais/shades-of-purple-vscode#41]
Tooltips that appear on hover have little to distinguish them from the editor panel apart from the darker background. In fact, the background is the same colour the background of the currently active line so it's not always easy to tell apart tooltip text from other text present in the editor.

Would it be possible to add a light border to surround the tooltip? Even something light/translucent would be enough to encapsulate the tooltip and make it stand out as a tooltip over other text.

To help appreciate the difference a thin border can make, I've attached a couple of screenshots to compare between Shades of Purple's current implementation as well as another theme called [Palenight](https://github.com/whizkydee/vscode-material-palenight-theme).

![Palenight Operator](https://user-images.githubusercontent.com/19497993/57136096-977a9200-6da3-11e9-8b76-5625f13635a1.png)
![Shades of Purple](https://user-images.githubusercontent.com/19497993/57136097-977a9200-6da3-11e9-99a1-3ab29df1754e.png)

Thanks for your time!

**Comment by ahmadawais** [comment]
Thanks for creating this issue. Borders create stress. Feels like more info than there actually is. So, in 🦄 Shades of Purple themes, there are no borders, there are colors.

But I see what you mean there. I just released a new update and have made the color more darker.

![](https://on.ahmda.ws/414cbd/url)

Peace! ✌️

**Comment by ahmadawais** [comment]
```
Publishing ahmadawais.shades-of-purple@5.3.0...
 DONE  Published ahmadawais.shades-of-purple@5.3.0
Your extension will live at https://marketplace.visualstudio.com/items?itemName=ahmadawais.shades-of-purple (might take a few seconds for it to show up).
```

**Comment by rdhar** [comment]
I appreciate the clarification on the reasoning behind the lack of borders. The darker tooltip background is fair enough compromise to separate the tooltip from the active line colour. Thanks for the quick turnaround!

**Comment by ahmadawais** [comment]
@rdhar Actually, I am already enjoying that darker background. Thanks for helping me make 🦄 Shades of Purple better. :)
