### ISSUE TITLE
Markdown link styling

### ISSUE THREAD

**Issue by rdhar** [ahmadawais/shades-of-purple-vscode#42]
From recent changes implemented in #40, here's a direct comparison from an identical section of a Markdown file.

<details><summary>Click to view screenshot as of v5.4.0:</summary>
<img src="https://user-images.githubusercontent.com/19497993/57166124-1b0ea000-6df1-11e9-8b7a-b987ea7cc17a.png"></img>
</details>

<details><summary>Click to view screenshot as of v5.1.0:</summary>
<img src="https://user-images.githubusercontent.com/19497993/57166119-15b15580-6df1-11e9-83bd-97011efd3643.png"></img>
</details>

I have to admit, while the latest update has certain improvements, I think I prefer a number of features from the older version as well. Here's what I think works really well and what not so much:

```diff
+ Links are underlined.
+ Linked text is yellow and surrounded by light-purple `[]`, consistently.
+ Link text is light-purple, consistently.
- Link text is surrounded by `[]` of the same colour. While I appreciate this
  is intentional to minimise attracting attention to it since it's invisible
  when the final Markdown is rendered, it ties into the next point...
- When you have a list of links, they look very dreary: the colours appear to
  be dull and repetitive. I heavily use Markdown very often and it's not un-
  common for this kind of links list to be featured in a number of files.
```

I get that it's not much help to criticise without providing suggestions for improvement so here's my take on it.

- Keep the light-purple `[]` but for the light-purple link text, change it to the green used in "Strings #A5FF90" since it _is_ a string _and_ that would make it consistent with its usage for class values in HTML, e.g., `href="www.site.link` where `www.site.link` is green.
- Carry this forward to the first portion of the links list (consistency is 🔑) while the URL that follows after the yellow `:` could be green (consistent with link text), yellow (consistent with link**ed** text) or remain light-purple (to minimise distraction), depending on what you deem to be most appropriate in your informed opinion.

For me, it's hard to visualise without seeing the different variations in front of me so I think you'd be the best judge of that. It'd be great to get others' opinions on this as well so you could make a more informed, popular decision but I guess that'd depend on others contributing actively on this thread, which could be rare!

Thanks again for your time, really appreciate it.

**Comment by ahmadawais** [comment]
True that. I have made a decision to make the links in alt style yellow.

![](https://on.ahmda.ws/602ebb/url)

 **DONE**:  Published ahmadawais.shades-of-purple@5.5.0
Your extension will live at https://marketplace.visualstudio.com/items?itemName=ahmadawais.shades-of-purple (might take a few seconds for it to show up).

**Comment by ahmadawais** [comment]
I don't like the output so I am again working on it. You my friend have opened a pandora box here 🤣

**Comment by ahmadawais** [comment]
OK I was able to target different things in Markdown with priority based context TM Scope. Something I had not done before. 

![img](https://on.ahmda.ws/70c26e/c)

I am happy with these new styles. You can also see at a glance that image styles are a tiny bit different which makes things very easy.  I wanted to make the text part of link image different color as well `[![Alt](https://awais.dev/sopicon)](https://awais.dev)` but that is technically not possible.

Peace! ✌️

**Comment by ahmadawais** [comment]
Moreover the image title is styled as well.

![](https://on.ahmda.ws/dfa83a/url)

**Comment by ahmadawais** [comment]
Here're the final styles.

![img](https://on.ahmda.ws/6ab20c/url)

 **DONE**  Published ahmadawais.shades-of-purple@5.6.0
Your extension will live at https://marketplace.visualstudio.com/items?itemName=ahmadawais.shades-of-purple (might take a few seconds for it to show up).

**Comment by rdhar** [comment]
Many thanks for looking into this, really liking the look of the recent changes! Here's an updated screenshot of various types of reference links running with the latest v5.6.0.

![image](https://user-images.githubusercontent.com/19497993/57194598-90d55180-6f40-11e9-91e5-09fc1b9e1c3e.png)

- [ ] Underlining is missing from the (white)spaces within link text.
- [ ] Title text is not coloured green for normal text links, like you've done for image links.
- [ ] `http://www.site.link` and `<http://www.site.link>` are not styled consistently as yellow links.

**Comment by ahmadawais** [comment]
>Underlining is missing from the (white)spaces within link text.
> Title text is not coloured green for normal text links, like you've done for image links.


Not happening on my end. Must be something on your end. Some extension acting out on your end. Try the insider version without extensions. Or deactivate all extension to find the culprit.






  Title text is not coloured green for normal text links, like you've done for image links.

>http://www.site.link and <http://www.site.link> are not styled consistently as yellow links.

Link like these `https://awais.dev <https://awais.dev>` are not markdown and cannot be styled. It's just simple text. Any styles on them will be universal on all para. You should avoid using non-markdown syntax.

**Comment by ahmadawais** [comment]
One thing I hadn't styled was Link's Title tag since it's a bad practice to use title on a link. But I just styled it. Releasing a new version that fixes this.

It must look like this.

![](https://on.ahmda.ws/cb01a0/url)

Also, you can see — Bare URL is a bad idea.

![](https://on.ahmda.ws/a34351/url)

**Comment by rdhar** [comment]
- [ ] Underlining is missing from the (white)spaces within link text.

  > Not happening on my end. Must be something on your end. Some extension acting out on your end. Try the insider version without extensions. Or deactivate all extension to find the culprit.

  Weirdly enough, I disabled all extensions except SOP and I could still replicate the issue whereby spaces within `[this is a sentence](www.site.link)` does not have the underline styling.

  <details><summary>My VS Code version details:</summary>
  Version: 1.33.1 (user setup)<br>
  Commit: 51b0b28134d51361cf996d2f0a1c698247aeabd8<br>
  Date: 2019-04-11T08:27:14.102Z<br>
  Electron: 3.1.6<br>
  Chrome: 66.0.3359.181<br>
  Node.js: 10.2.0<br>
  V8: 6.6.346.32<br>
  OS: Windows_NT x64 10.0.17763</details>

- [x] Title text is not coloured green for normal text links, like you've done for image links.

  > One thing I hadn't styled was Link's Title tag since it's a bad practice to use title on a link. But I just styled it. Releasing a new version that fixes this.

- [x] `http://www.site.link` and `<http://www.site.link>` are not styled consistently as yellow links.

  > Link like these https://awais.dev <https://awais.dev> are not markdown and cannot be styled. It's just simple text. Any styles on them will be universal on all para.

**Comment by ahmadawais** [comment]
**DONE**  Published ahmadawais.shades-of-purple@5.7.0
Your extension will live at https://marketplace.visualstudio.com/items?itemName=ahmadawais.shades-of-purple (might take a few seconds for it to show up).

**Comment by ahmadawais** [comment]
>OS: Windows_NT x64 10.0.17763

Maybe it's a windows thing. I tested on two Macs. @ahmadbilaldev @msaaddev can you folks test on windows that the links text has all underline or not on Windows.

**CORRECT** ↓

![](https://on.ahmda.ws/7989a2/url)

**INCORRECT** ↓

![](https://on.ahmda.ws/c248a2/url)

If you see the incorrect version this will confirm it's a bug on Windows and then @rdhar you will have to file this issue with @microsoft/code repo.

Peace! ✌️
