### ISSUE TITLE
Keep colour of bold/italic text in Markdown

### ISSUE THREAD

**Issue by rdhar** [ahmadawais/shades-of-purple-vscode#43]
Another question, is there any reasoning for changing the colour of bold or italic text from the regular white to light-purple colour in Markdown?

I really appreciate how the text changes its font-weight or font-style depending on bold or italic formatting but it seems odd that it changes colour as well, especially to a lower contrasting one.

When you're reading the rendered Markdown output, bold/italic text appear in the exact same colour, just different formatting, so one would think that the raw Markdown equivalent would keep the bold/italic text in white but just change its formatting as appropriate. As with other places, I think it's best to retain to the dark `**` on either side though, to keep a similar effect with the unobtrusive `#` for headings.

Thanks for your time.

**Comment by rdhar** [comment]
If there's a custom User Settings that can be toggled to compare this against (i.e., keep bold+italic text white in Markdown), that'd be really appreciated as well. Thanks!

**Comment by ahmadawais** [comment]
Sure, looking into this.

You can give it a try

```json
{
			"name": "[MARKDOWN] - Color for Emphasis Bold",
			"scope": ["markup.bold.markdown", "markup.italic.markdown"],
			"settings": {
				"fontStyle": "bold",
				"foreground": "#A599E9"
			}
		},
```

This goes in the same token setting I sent you in that other issue.

**Comment by ahmadawais** [comment]
I dunno — purple looks much more fun and clear to me. What about you?

**Comment by rdhar** [comment]
![image](https://user-images.githubusercontent.com/19497993/57336056-8bccf980-711c-11e9-9e38-9533415d5a62.png)

I gotta say, I'm digging the look of white-coloured emphasised text. To me, it seems to flow better in a sentence rather than drastically changing colours in between. But that's just me; better to get other opinions first before making anything official :)

**Comment by ahmadawais** [comment]
After using it for a couple of days, I tend to somewhat agree on keeping the colors same so I made that default.

 **DONE**  Published ahmadawais.shades-of-purple@5.8.0
Your extension will live at https://marketplace.visualstudio.com/items?itemName=ahmadawais.shades-of-purple (might take a few seconds for it to show up).
