### ISSUE TITLE
🐛 HTML comment punctuation is coloured erroneously

### ISSUE THREAD

**Issue by rdhar** [ahmadawais/shades-of-purple-vscode#44]
![image](https://user-images.githubusercontent.com/19497993/57306121-2b1ccd00-70da-11e9-9ed6-67ba7de39147.png)

`<!-- -->`  appears to be Contrast (#FAD000) coloured instead of the expected Comment (#B362FF) colour. Found this to be reproducible on v5.7.0.

**Comment by ahmadawais** [comment]
That's just you. You must have some custom colors set or an extension causing it.

Here's what I get.

![](https://on.ahmda.ws/75c72d/url)

**Comment by ahmadawais** [comment]
@ahmadbilaldev can you test this.

**Comment by rdhar** [comment]
My apologies, you're absolutely right. It's one of my extensions that's behind this. I'll update this message once I root out its name. Thanks for looking into this!

**Comment by ahmadbilaldev** [comment]
Working fine on my side. Must be some extension fiddling with the settings, as mentioned above.
