### ISSUE TITLE
macOS Terminal.app Theme

### ISSUE THREAD

**Issue by 0x77dev** [ahmadawais/shades-of-purple-vscode#45]
https://github.com/ahmadawais/Shades-of-Purple-iTerm2/issues/3#issue-441428173

**Comment by ahmadawais** [comment]
@0x77dev Misha that's super awesome. I'll create a new repo where we can put this and add you as a collaborator there.

**Comment by 0x77dev** [comment]
Tracked here: https://github.com/ahmadawais/Shades-of-Purple-iTerm2/issues/3
