### ISSUE TITLE
Improve color in RaibowCSV

### ISSUE THREAD

**Issue by qell** [ahmadawais/shades-of-purple-vscode#47]
Hi @ahmadawais. Your theme is great. But can be better. On default settings in Rainbow CSV first and second column have the same color. I know it can be fix by yourself but different colors out-of-the box will be nice.

![image](https://user-images.githubusercontent.com/41490584/57685771-e395c400-7638-11e9-8f2b-837f1f4b1a6c.png)

**Comment by ahmadawais** [comment]
- Tell me what format of file this is.
- Give me a chunk of this file to play with.
- Tell me if you're using a syntax extension for this format

Then I can help.

**Comment by qell** [comment]
1. File format is CSV with separator by comma
2. My workaround is:
`     {
            "scope": "keyword.rainbow2",
            "settings": {
               "foreground": "#3CB44B"            }
        },`

3. Example file(change file extension from .txt to .csv):
[hall_5_celsius.txt](https://github.com/ahmadawais/shades-of-purple-vscode/files/3197728/hall_5_celsius.txt)

**Comment by ahmadawais** [comment]
Do you use any syntax extension for this format?

**Comment by ahmadawais** [comment]
Next version improvements comming in next week.

<img width="583" alt="Screenshot 2019-07-06 at 6 05 22 PM" src="https://user-images.githubusercontent.com/960133/60756618-de416e00-a018-11e9-8691-fec7b6fd9647.png">
