### ISSUE TITLE
Improper attribution

### ISSUE THREAD

**Issue by liviuschera** [ahmadawais/shades-of-purple-vscode#5]
Hi mate. 
Is there a good reason why you didn't give credit to Wes Bos' Cobalt2 theme from which you forked Shades of Purple?

In your Licence & Attribution section you say: 
> This theme takes inspiration from many VSCode themes including but not limited to Cobalt themes by Roberto Achar...

Originally you didn't credited Roberto Achar's theme and then you amended the attribution improperly. Why?

The thing is that Robaro Achar clearly states that:

![ra cobal2](https://user-images.githubusercontent.com/12068956/39659969-1ec2cb7c-5074-11e8-8b4f-fb8d53c24fee.JPG)

Here is what I'm talking about:

![cobalt2 vs sop](https://user-images.githubusercontent.com/12068956/39659974-398314ee-5074-11e8-9943-92ea01d2a283.png)

**Comment by ahmadawais** [comment]
Yes there's a very good reason. Wes Bos is an online bully. I stated off of Robert's work. And would never attribute a bully.

**Comment by liviuschera** [comment]
The fact that you came up with such a story hopping that it will justify an intellectual property misappropriation is bewildering. 
Basically what you are saying is that if you dislike someone or you feel that someone  did you wrong is not only OK but justifiable to plagiarize that someone's work. 

Wes Bos did his 1st commit of his Cobalt2 theme on Jan 5, 2013 as you can see [here](https://github.com/wesbos/cobalt2/commit/f41c536112b4de736bd3e54320224291483bf29a)

You did forked/copied/duplicate Wes Bos's theme in it's entirety, as it can be seen from the screenshot. Not Roberto Achar's theme. In some cases you did structure workbench, terminal, editor and syntax color almost identically to Cobalt2's theme. You even copied his comments, and optional titles, claiming that the idea of structuring the theme in certain way and adding comments belong to you.

Don't you forget that in your initial attribution you didn't mention anything about Cobalt2 theme, it was only after you were caught red handed you did a half-baked attribution.

The issue you are so hung up on is not in my repository but is the fact that you are not being able to own your own mistakes and that this make believe armchair reasoning is coming from your over inflated ego oozing of self entitlement. 

As far as I am concerned there is nothing more to add to this story.
