### ISSUE TITLE
Theme for RStudio

### ISSUE THREAD

**Issue by BingoLaHaye** [ahmadawais/shades-of-purple-vscode#53]
Is there any chance there will be support coming for RStudio? I really like this theme and would love to use it with in Rstudio.

**Comment by ahmadawais** [comment]
If you want to make one. I can provide anything you need with syntax colors and all. Otherwise, I don't use RStudio so can't make a theme for it. 

I am glad you like it.

**Comment by BingoLaHaye** [comment]
That would be absolutely fantastic! I'll start making one once I get the chance to!

**Comment by ahmadawais** [comment]
Awesome! 💯
Looking forward, peace! ✌️
