### ISSUE TITLE
Better support for C++

### ISSUE THREAD

**Issue by AxelDaguerre-HeavyLearner** [ahmadawais/shades-of-purple-vscode#54]
Hi there is an issue for C++ : types don't separate from variable name. 
Best regards

**Comment by ahmadawais** [comment]
Send me a chunk of code. Tell me which syntax grammar extension you use for C++. Also send a screenshot of the part that's buggy. 

When I have all these three things, I'll fix it in a couple of hours.

**Comment by AxelDaguerre-HeavyLearner** [comment]
Thank you for the answer actually i just figured out : i installed *C++
Better Syntax *from VS Code and it works like a charm. I think i had not VS
Code set up correctly, if you need screenshot i can maybe uninstall the
package and show you if it is really something that matters for you.
https://gitlab.com/AxelDaguerre
https://www.codewars.com/users/AxelDaguerre-HeavyLearner

**Comment by ahmadawais** [comment]
No, you actually need the syntax grammar for it to work correctly. VSCode doesn't have all the grammar support by default which keeps it fast.


If you like this theme, or my support, my open source work, then you can support it by taking my [VSCode Power User Course](https://VSCode.pro). You'll learn my dev-workflow with VSCode and everything important you need to know. Pretty much my best work.

Check it out [VSCode Power User Course](https://VSCode.pro) →

> _P.S. You can always write a five-star review as sort of an appreciation for all the time I put into this theme — if interested click here to do that → [![Rating](https://img.shields.io/vscode-marketplace/r/ahmadawais.shades-of-purple.svg?label=Ratings&colorA=2D2A56&colorB=4D2AFF)](https://marketplace.visualstudio.com/items?itemName=ahmadawais.shades-of-purple#review-details)_
