### ISSUE TITLE
Theme is not working properly with VSCode 1.41.1

### ISSUE THREAD

**Issue by JalpeshVadgama** [ahmadawais/shades-of-purple-vscode#82]
First of All, I would like to thank you for creating such an awesome theme. I really liked it. But recently with VScode Version 1.4.1. It seems to be broken there are some parts where colors are not proper in the editor.

Here is my Visual Studio Code version
Version: 1.41.1 (user setup)
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T14:58:56.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18362

I'm using on my ThinkPad and resolution is 2560 * 1440. 

Please see attached screenshot. You can see that there are some places where colors are not proper. I'm sure others who have got updated will have the same issue.

<img width="1074" alt="Bug" src="https://user-images.githubusercontent.com/5141580/71587132-8e181400-2b42-11ea-8b99-df4fa262220b.png">

here you can see that at the bottom and side color are different.

And here is another screenshot. Here on the left side, the color is different.

<img width="1111" alt="Bug2" src="https://user-images.githubusercontent.com/5141580/71587222-d7686380-2b42-11ea-805a-2cc583f38298.png">

You are doing a great job and I think this all are small things to make it awesome

**Comment by ahmadawais** [comment]
I tried everything but could not reproduce the problem. I don't have access to a windows system. Can you try the latest build of VSCode Insiders version? Maybe it is a bug with VSCode?

**Comment by ahmadawais** [comment]
Can you also confirm if this issue exists in a different theme? 🤔 Let's say Dracula.

**Comment by JalpeshVadgama** [comment]
> I tried everything but could not reproduce the problem. I don't have access to a windows system. Can you try the latest build of the VSCode Insiders version? Maybe it is a bug with VSCode?

I have also tried VSCode Insiders build also same problem exists.

**Comment by ilya144** [comment]
same problem on vs code 1.40.2 on Fedora 30 KDE Plasma

**Comment by ahmadawais** [comment]
@JalpeshVadgama has created an issue on the VSCode repo since this feels like a VSCode issue. I'm subscribed to it so let's see how that goes. Will try to fix it as soon as I know how to reproduce this.

**Comment by nilesh-maurya** [comment]
I had the same problem on my laptop(Ubuntu 18.04).

`code index.html --disable-gpu`

opening vs code with argument --disable-gpu worked for me.

**Comment by ilya144** [comment]
@nilesh-maurya --disable-gpu work for me too, i3 6006u with intel hd graphics 520 as gpu

**Comment by guilhermemiua** [comment]
> I had the same problem on my laptop(Ubuntu 18.04).
> 
> `code index.html --disable-gpu`
> 
> opening vs code with argument --disable-gpu worked for me.

Hi! I did this, it removes the parts where does not works properly, but also changes the color.. Did someone fixed this bug?

**Comment by ahmadawais** [comment]
Doesn't look like a bug in the theme. Please go ahead and report this to Microsoft here https://github.com/microsoft/vscode/issues/new/choose
