### ISSUE TITLE
Please make theme for Suckless Terminal thanks!

### ISSUE THREAD

**Issue by kevinaltaf** [ahmadawais/shades-of-purple-vscode#84]

**Comment by ahmadawais** [comment]
What is that?

**Comment by kevinaltaf** [comment]
Terminal similiar iTerm <https://st.suckless.org/>

**Comment by ahmadawais** [comment]
This is an open-source theme right. How about you help out and build a
theme for the Suckless terminal. I am here if you get stuck. But I don't
use that software so I won't be able to find time to work on it.

>

**Comment by ahmadawais** [comment]
Closing this ticket but we can keep conversing.
