### ISSUE TITLE
Ruby color scheme broken after latest update

### ISSUE THREAD

**Issue by nachoal** [ahmadawais/shades-of-purple-vscode#87]
Hey, The theme was working fine until Monday when after the last update the scheme started randomly changing shades:

On methods: 
![image](https://user-images.githubusercontent.com/3743461/76114003-cc9ad680-5faa-11ea-874d-868f3f81818d.png)

On methods 2:
![image](https://user-images.githubusercontent.com/3743461/76114071-ea683b80-5faa-11ea-9060-429a5b01f041.png)

On methods 3: 
![image](https://user-images.githubusercontent.com/3743461/76114087-f0f6b300-5faa-11ea-8120-e6ad4599393a.png)

Notice that it changes between the color for language keywords: `orange` and the color for method calls `yellow`

**Comment by ahmadawais** [comment]
Send me the source code that has this problem and the Ruby syntax highlighting extension you use, I will fix this and release a new version.

**Comment by ahmadawais** [comment]
It is probably a problem with the syntax grammar or addition that needs to be addressed.

**Comment by ahmadawais** [comment]
OK, now experiencing the same thing myself. Looking into it.

**Comment by ahmadawais** [comment]
So there's a new feature that caused this problem. I think you can revert back by disabling it by setting

`"editor.semanticHighlighting.enabled": false,`
