### ISSUE TITLE
background appearing like patches 

### ISSUE THREAD

**Issue by yashwanth2804** [ahmadawais/shades-of-purple-vscode#89]
![vscodepurple](https://user-images.githubusercontent.com/8038593/79335619-f21ee680-7f3f-11ea-851a-6fde5da3e983.png)

**Comment by ahmadawais** [comment]
It's probably a GPU issue. File this with VSCode repo, nothing to do with the theme. 

I tested it as well.

![image](https://user-images.githubusercontent.com/960133/79346569-fb15b500-7f4b-11ea-8b27-400dbf508931.png)
