### ISSUE TITLE
[TypeScript] Recent update makes variable declarations less readable

### ISSUE THREAD

**Issue by Penlane** [ahmadawais/shades-of-purple-vscode#91]
Hi! I really like the theme and use it a lot.
The latest update (6.10.0) unfortunately broke the variable declarations for me

Before:
![eMqXu92](https://user-images.githubusercontent.com/34662006/80417849-bc321880-88d6-11ea-81eb-5a33d2e6e55d.png)

After:
![EFM4Kbn](https://user-images.githubusercontent.com/34662006/80417858-c05e3600-88d6-11ea-8c03-c1657e6db6d2.png)

You can see that the "const" keyword is not hightlighted and different from the variable anymore. Is this intended?

**Comment by ahmadawais** [comment]
That's weird. Can you share that code file and a list of extensions you use.

**Comment by ahmadawais** [comment]
`DONE`  Published ahmadawais.shades-of-purple@6.11.0
Your extension will live at https://marketplace.visualstudio.com/items?itemName=ahmadawais.shades-of-purple (might take a few minutes for it to show up).



> _P.S. You can always write a five-star review as sort of an appreciation for all the time I put into this theme — if interested click here to do that → [![Rating](https://img.shields.io/vscode-marketplace/r/ahmadawais.shades-of-purple.svg?label=Ratings&colorA=2D2A56&colorB=4D2AFF)](https://marketplace.visualstudio.com/items?itemName=ahmadawais.shades-of-purple#review-details)_

**Comment by ahmadawais** [comment]
![image](https://user-images.githubusercontent.com/960133/80423382-6327ac00-88f9-11ea-93b8-cf8d7b9ea871.png)

**Comment by Penlane** [comment]
That was quick, I just updated and the issue is resolved. Thank you very much, looks great :)

**Comment by ahmadawais** [comment]
Great. Consider writing that review and checking out my VSCode.pro course.
That allows me to work on this theme for free.

>
