### ISSUE TITLE
SOP for Google Chrome and Base16

### ISSUE THREAD

**Issue by demartini** [ahmadawais/shades-of-purple-vscode#95]
Hello @ahmadawais, I hope you are well.

First of all thank you very much for this amazing theme I really love everything about him. That's why I decided to make some contributions.

- The first is the theme for [Google Chrome](https://github.com/demartini/shades-of-purple-google-chrome), for those who want to use the theme they can install through the [Google Chrome Store](https://chrome.google.com/webstore/detail/aomhpijmdccjapkfcbalcoimhdlbkfjn).
- The second is the [Base16](https://github.com/demartini/base16-shades-of-purple) color scheme.

These themes follow the [SOP's Syntax Colors](https://github.com/ahmadawais/shades-of-purple-vscode#sops-syntax-colors) guidelines as closely as possible.

I hope you like it.

**Comment by ahmadawais** [comment]
Hi @demartini this is pretty awesome of you. I'm glad you like the theme and your contributions are completely welcomed. 

There's one tiny problem. I am creating an entire suite of Shades of Purple themes and would like to own all the instances of it. This is why I have registered the trademark and started developing https://ShadesOfPurple.pro — I'd be happy to give you a free Pro theme license once it is live for your work. So, can you please transfer the Chrome theme (I was already working on one) to me and help me maintain it as one of the primary maintainers. 

Please respond so I can set up the repositories and start inviting you.

**Comment by demartini** [comment]
Hi,

I'm very happy to know that you liked it!

And what incredible news, about the suite I would already make a suggestion like that. I'm even porting the color scheme to other applications, such as Telegram, Firefox, Insomnia, Macdown, etc.

If you saw the [output](https://github.com/demartini/base16-shades-of-purple-exported-themes) of the Base16, we already have a lot of applications.

Please set up the repositories so that I can transfer them to you.

**Comment by demartini** [comment]
Hey @ahmadawais, have you already set up the repositories?

**Comment by ahmadawais** [comment]
Awesome 👍
I've been traveling. Give me a day, I'll send you the link and set up.

**Comment by ahmadawais** [comment]
Hi @demartini 

Check email for invites to 

1. https://github.com/ahmadawais/shades-of-purple-google-chrome/invitations
2. https://github.com/ahmadawais/shades-of-purple-base16/invitations

Please transfer the repos to these repos. Once you do ping me so I can organize the readme for the site I am building. Also tell me what do you need for transferring the Chrome extension to me? Check the DM on twitter for my email :)

**Comment by demartini** [comment]
I believe we can close this issue as [Shades of Purple Theme for Google Chrome](https://github.com/ahmadawais/shades-of-purple-google-chrome) and [Shades of Purple for Base16](https://github.com/ahmadawais/base16-shades-of-purple) have been officially released.
