### ISSUE TITLE
Renamed variable in Destructuring does not have different color

### ISSUE THREAD

**Issue by shubham-sns** [ahmadawais/shades-of-purple-vscode#97]
`const {
destructuredItem : renamedThisValue ,
} = someRandomObject
`

_renamedThisValue_ should have different color cause its a variable name ,

**Comment by ahmadawais** [comment]
No, it shouldn't. Both of these are variable contexts. The `destructuredItem` is a var even if it points to an object. And `renamedThisValue` is just an alias for the same thing. Having different colors there would signify something different about the alias. 

That's what I think atm.

**Comment by shubham-sns** [comment]
> No, it shouldn't. Both of these are variable contexts. The `destructuredItem` is a var even if it points to an object. And `renamedThisValue` is just an alias for the same thing. Having different colors there would signify something different about the alias. 
> 
> That's what I think atm.

Is there any way to change it in settings ?

**Comment by ahmadawais** [comment]
You have to study the docs on how you can override theme colors. I don't
have a link handy.

>
